name: fake_deploy

on:
  push:

jobs:
  deploy_test_server:
    runs-on: ubuntu-latest

    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Print Deploy Message
        run: 'echo now deploying branch: ${{ github.ref }} to the test server'

      - name: Set Env to Development
        run: 'npm run setDev'

  deploy_production:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Print Deploy Message
        run: 'echo now deploying to production'

      - name: Set Env to Production
        run: 'npm run setProd'
